### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [7]:
vector = np.random.rand(10, 1)

In [8]:
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])

In [9]:
vector, matrix

(array([[0.67214112],
        [0.67914579],
        [0.29538159],
        [0.68338847],
        [0.00979337],
        [0.65250782],
        [0.28623529],
        [0.65838   ],
        [0.02145696],
        [0.44500476]]),
 array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]))

In [10]:
vector.shape, matrix.shape

((10, 1), (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [14]:
vector = vector + 10

In [15]:
rounded_vector = np.round(vector, 2)

rounded_vector

array([[10.67],
       [10.68],
       [10.3 ],
       [10.68],
       [10.01],
       [10.65],
       [10.29],
       [10.66],
       [10.02],
       [10.45]])

In [16]:
matrix = matrix * 2

matrix

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [19]:
squared_vector = vector ** 2

squared_vector

array([[113.89459606],
       [114.04415481],
       [105.994882  ],
       [114.13478912],
       [100.19596334],
       [113.47592283],
       [105.80663639],
       [113.60106413],
       [100.42959964],
       [109.0981245 ]])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [20]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [26]:
result_matrix = np.dot(B, A)

result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [27]:
np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

In [28]:
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [31]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [32]:
vector.T

array([[10.67214112, 10.67914579, 10.29538159, 10.68338847, 10.00979337,
        10.65250782, 10.28623529, 10.65838   , 10.02145696, 10.44500476]])

In [34]:
column_vector = np.expand_dims(vector, axis=1)

column_vector

array([[[10.67214112]],

       [[10.67914579]],

       [[10.29538159]],

       [[10.68338847]],

       [[10.00979337]],

       [[10.65250782]],

       [[10.28623529]],

       [[10.65838   ]],

       [[10.02145696]],

       [[10.44500476]]])

In [37]:
column_vector.T, column_vector.T.shape

(array([[[10.67214112, 10.67914579, 10.29538159, 10.68338847,
          10.00979337, 10.65250782, 10.28623529, 10.65838   ,
          10.02145696, 10.44500476]]]),
 (1, 1, 10))